---
job: "extension"
config:
  name: "sd15_inpainting_tomtc_lora"
  process:
    - type: "diffusion_trainer"
      training_folder: "/workspace/ai-toolkit/output"
      sqlite_db_path: "./aitk_db.db"
      device: "cuda"
      trigger_word: "TomTC"
      performance_log_every: 10
      network:
        type: "lora"
        linear: 8
        linear_alpha: 8
        conv: 8
        conv_alpha: 8
        lokr_full_rank: true
        lokr_factor: -1
        network_kwargs:
          ignore_if_contains: []
      save:
        dtype: "bf16"
        save_every: 250
        max_step_saves_to_keep: 20
        save_format: "diffusers"
        push_to_hub: false
      datasets:
        - folder_path: "/workspace/ai-toolkit/datasets/tomthecat"
          mask_path: null
          mask_min_value: 0.1
          default_caption: ""
          caption_ext: "txt"
          caption_dropout_rate: 0.05
          cache_latents_to_disk: false
          is_reg: false
          network_weight: 1
          resolution:
            - 512
          controls: []
          shrink_video_to_frames: true
          num_frames: 1
          flip_x: false
          flip_y: false
          num_repeats: 1
      train:
        batch_size: 1
        bypass_guidance_embedding: false
        steps: 3000
        gradient_accumulation: 4
        train_unet: true
        train_text_encoder: false
        gradient_checkpointing: true
        noise_scheduler: "ddpm"
        optimizer: "adamw8bit"
        timestep_type: "sigmoid"
        content_or_style: "balanced"
        optimizer_params:
          weight_decay: 0.0001
        unload_text_encoder: false
        cache_text_embeddings: false
        lr: 0.0001
        ema_config:
          use_ema: false
          ema_decay: 0.99
        skip_first_sample: false
        force_first_sample: false
        disable_sampling: false
        dtype: "bf16"
        diff_output_preservation: false
        diff_output_preservation_multiplier: 1
        diff_output_preservation_class: "person"
        switch_boundary_every: 1
        loss_type: "mse"
      logging:
        log_every: 1
        use_ui_logger: true
      model:
        name_or_path: "stable-diffusion-v1-5/stable-diffusion-v1-5"
        quantize: false
        qtype: "qfloat8"
        quantize_te: false
        qtype_te: "qfloat8"
        arch: "sd15"
        low_vram: false
        model_kwargs: {}
      sample:
        sampler: "ddpm"
        sample_every: 250
        width: 512
        height: 512
        samples:
          - prompt: "TomTC"
          - prompt: "TomTC is sitting on the rug and smiling"
          - prompt: "Forest and sunny weather"
        neg: ""
        seed: 42
        walk_seed: false
        guidance_scale: 6
        sample_steps: 25
        num_frames: 1
        fps: 1
meta:
  name: "[name]"
  version: "1.0"
